AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the {{cookiecutter.resource_name}} resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: {{cookiecutter.project_name}}.handlers.resource
      Runtime: python3.12
      CodeUri: src/

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: {{cookiecutter.project_name}}.handlers.test_entrypoint
      Runtime: python3.12
      CodeUri: src/


