AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Deploys pieces necessary to make sure Contract Tests work within AWS.
  Deploy this role and use its ARN in your contract test command line.  See README.md

Resources:

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - resources.cloudformation.amazonaws.com
                - cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: ResourceTypePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - "dynamodb:CreateTable"
                - "dynamodb:DeleteItem"
                - "dynamodb:DescribeTable"
                - "dynamodb:GetItem"
                - "dynamodb:PutItem"
                - "dynamodb:UpdateItem"
                - "dynamodb:UpdateTable"
                - "identitystore:DescribeGroup"
                - "identitystore:ListGroups"
                Resource: "*"

              # Specific to contract Tests
              # https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-test.html#debug-contract-test
              - Effect: Allow
                Action:
                  - "s3:PutObject"
                  - "kms:Encrypt"
                  - "kms:Decrypt"
                  - "kms:ReEncrypt*"
                  - "kms:GenerateDataKey*"
                  - "kms:DescribeKey"
                Resource: "*"
