AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Deploys extension for use with contract tests - Cloudformation way.  See Readme.MD

Parameters:

  RoleArn:
    Type: String


  CFExtensionBucket:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /cloud/public/regional/s3/v1/buckets/cf_extensions/name

Resources:

  #Register type to be used
  ResourceVersion:
    Type: AWS::CloudFormation::ResourceVersion
    Properties:
      TypeName: {{cookiecutter.resource_name}}
      ExecutionRoleArn: !Ref RoleArn
      SchemaHandlerPackage: !Sub "s3://${CFExtensionBucket}/NickTest/dotmatics-sso-groupinfo.zip"

  #Guarantee latest = default
  ResourceDefaultVersion:
    Type: AWS::CloudFormation::ResourceDefaultVersion
    Properties:
      TypeVersionArn: !Ref ResourceVersion