###
# Deploys the Custom resource like the automation framework does.
# Can only be used on feature, release, hotfix, and develop branches
# TODO: Check the S3 URL to make sure its right for your repository name
##

AWSTemplateFormatVersion: 2010-09-09

Parameters:
  BranchName:
    Type: String
    Description: IE- feature/test

Resources:

  DeployResource:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/com.elizacloud.${AWS::Region}.cfresources/CustomCFResources/Repositories/Eliza-{{ cookiecutter.project_name }}/${BranchName}/template.yaml'

