AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Deploys extension with required resources.

Parameters:

  S3CFExtensionBucket:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /cloud/public/regional/s3/v1/buckets/cf_extensions/name

  S3Key:
    Type: "String"
    Description: "Should be like NickTest/dotmatics-sso-groupinfo.zip"
    Default: "Replaced By CI"


  SSMPrefix:
    Type: String


Resources:

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: resources.cloudformation.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount: !Sub "${AWS::AccountId}"
              StringLike:
                aws:SourceArn: !Sub "arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:type/resource/Dotmatics-*"
      Path: "/"
      Policies:
        - PolicyName: ResourceTypePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:CreateTable"
                  - "dynamodb:DeleteItem"
                  - "dynamodb:DescribeTable"
                  - "dynamodb:GetItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:UpdateItem"
                  - "dynamodb:UpdateTable"

                  #TODO: Add other AWS IAM Permissions required here

                Resource: "*"

        - PolicyName: Logging
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                   - "logs:CreateLogStream"
                   - "logs:DescribeLogGroups"
                   - "logs:DescribeLogStreams"
                   - "logs:PutLogEvents"
                   - "cloudwatch:ListMetrics"
                   - "cloudwatch:PutMetricData"
                Resource: "*"

  SSMRoleArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "${SSMPrefix}/public/regional/iam/v1/roles/cf_extensions/{{cookiecutter.project_name}}/arn"
      Type: String
      Value: !GetAtt ExecutionRole.Arn
      Description: "Extension Execution Role ARN"

  #Logging
  ExtensionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7


  #Register type to be used
  ResourceVersion:
    Type: AWS::CloudFormation::ResourceVersion
    Properties:
      TypeName: {{cookiecutter.resource_name}}
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      SchemaHandlerPackage: !Sub "s3://${S3CFExtensionBucket}/${S3Key}"
      LoggingConfig:
        LogGroupName: !Ref ExtensionLogGroup
        LogRoleArn: !GetAtt ExecutionRole.Arn

  #Guarantee latest = default
  ResourceDefaultVersion:
    Type: AWS::CloudFormation::ResourceDefaultVersion
    Properties:
      TypeVersionArn: !Ref ResourceVersion